import dayjs from 'dayjs'
export interface ReceiveType {
    type?: string,
    did: string,
    cuser: string,
    muser: string,
    cdate: Date,
    mdate: Date,
    plastupdate: number,
    dbDoc: string,
    dbOrganDid: string,
    dbOrganCode: string,
    dbDelDate: Date,
    dbSupplierDid: string,
    dbSupplierCode: string,
    dbStatus: string,
    dbCheckStatus: string,
    dbReceiveStatus: string,
    dbPostStatus: string,
    dbTosDid: string,
    dbTosCode: string,
    dbSrcType: string,
    dbSrcDoc: string,
    dbBusinessDoc: string,
    dbCustomerDid: string,
    dbCustomerCode: string,
    dbWarehouseDid: string,
    dbWarehouseCode: string,
    dbRemark: string,
}
export interface ReceiveListParm {
    pageSize: number,
    currentPage: number,
    did: string,
    cuser: string,
    muser: string,
    beginCdate: dayjs.Dayjs,
    endCdate: dayjs.Dayjs,
    mdate: dayjs.Dayjs,
    plastupdate: number,
    dbDoc: string,
    dbOwnerDid: string,
    dbBeginDelDate: dayjs.Dayjs,
    dbEndDelDate: dayjs.Dayjs,
    dbSupplierDid: string,
    dbStatus: string,
    dbCheckStatus: string,
    dbReceiveStatus: string,
    dbPostStatus: string,
    dbTosDid: string,
    dbSrcType: string,
    dbSrcDoc: string,
    dbBusinessDoc: string,
    dbCustomerDid: string,
    dbWarehouseDid: string,
    dbRemark: string,
}